apiVersion: apps/v1
kind: Deployment
metadata:
  name: paycenter
  labels:
    app: paycenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paycenter
  template:
    metadata:
      labels:
        app: paycenter
    spec:
      containers:
        - name: paycenter
          image: username/paycenter:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5